<?php
/**
 * Created by PhpStorm.
 * User: Y
 * Date: 2015/8/13 0013
 * Time: 16:59
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Home' => '首页',
    'About' => '关于',
    'Contact' => '联系我们',
    'Logout' => '退出',
    'Login' => '登录',
    'username' => '用户名',
    'password' => '密码',
    'rememberMe' => '记住我',
    'Welcome to' => '欢迎',
);